const RESPONSE_CODES_CATALOG = {
    OK: 200,
    ERROR: 500,
    CREATED: 201,
    UNAUTHORIZED: 401,
    BAD_REQUEST: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INCONSISTENCY: 1001,
  };
  
  const RESPONSE_MESSAGE_CATALOG = {
    OK: 'CORRECT OPERATION',
    CREATED: 'RESOURCE CREATED SUCCESSFULLY',
    ERROR: 'INTERNAL SERVER ERROR',
    BAD_REQUEST: 'REQUEST IS MAL FORMED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'RESOURCE NOT FOUND',
    INCONSISTENCY: 'INCONSISTENCY FOUND',
    CONFLICT: 'RESOURCE ALLREADY EXISTS',
  };
  
  export { RESPONSE_CODES_CATALOG, RESPONSE_MESSAGE_CATALOG };
  